# Generated by Django 5.2.6 on 2025-10-02 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_type_alter_post_content_polloption'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ends_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='max_choices',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='post',
            name='starts_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
